### ISSUE TITLE
crash on loading up with (Rarmor 2-1.0.0Beta1.jar)

### ISSUE THREAD

**Issue by SDUBZ** [canitzp/Rarmor#14]
crashed on loading up with minecraft 1.10.2
here: http://pastebin.com/miZrjsjE
forge: 1.10.2-Forge 12.18.1.2014
client log: 
[fml-client-latest.txt](https://github.com/canitzp/Rarmor/files/367118/fml-client-latest.txt)

**Comment by KidsDontPlay** [comment]
baubles stuff is not compatible with the new rarmor version because rarmor was completely rewritten.
You need remove rarmor or baubles stuff

**Comment by canitzp** [comment]
You can just disable the rarmor integrationin the baubles stuff config
