### ISSUE TITLE
crash in gui while changing colour of chestplate(1.11.2)Rarmor-1.11.2-r4.1

### ISSUE THREAD

**Issue by SDUBZ** [canitzp/Rarmor#18]
crash report:
[crash-2017-02-06_06.22.18-server.txt](https://github.com/canitzp/Rarmor/files/753213/crash-2017-02-06_06.22.18-server.txt)

rarmor:Rarmor-1.11.2-r4.1
forge:1.11.2-2226

also chest plate not showing up in jei
when searching @rarmor and rormor

had to run /give to get chestplate

**Comment by canitzp** [comment]
Thanks for the report, I take a look into both errors

**Comment by canitzp** [comment]
I fixed possibly the first bug, but it isn't only my vault, xreliquary has caused it too, I only don't know what they do. For me the complete armor gets shown inside of JEI
