### ISSUE TITLE
Rarmor crashing Server-side on 1.12

### ISSUE THREAD

**Issue by kd8lvt** [canitzp/Rarmor#21]
Crashlog:
[crash-2017-07-03_11.59.02-server.txt](https://github.com/canitzp/Rarmor/files/1120070/crash-2017-07-03_11.59.02-server.txt)

Seems to me that Rarmor is trying to access client-side class files even when on the server-side...

This is my modlist, just in case:
[modlist.txt](https://github.com/canitzp/Rarmor/files/1120083/modlist.txt)

This only happens server-side, not client-side. If you need any more information, just ask, I'd be more than happy to (try and) help.

-Kd

**Comment by canitzp** [comment]
Thanks for the report, I fix it as soon as possible
