### ISSUE TITLE
 1.12-R.5.0 crashes dedicated server Forge 1.12 build 2443

### ISSUE THREAD

**Issue by kreezxil** [canitzp/Rarmor#23]
I see two similar reports, is mine a new issue?

Notes:
     on startup looking for client side classes

crash report:
https://gist.github.com/0a87183a16e5eb50fa5836fae25b061e

fml server latest:
https://gist.github.com/20d891f3c3fc2f5f1c193e91452d7fbe

**Comment by canitzp** [comment]
If I have some mood and time i'll fix it. Don't expect that this is soon

**Comment by canitzp** [comment]
same as #21
