### ISSUE TITLE
1.9-0.5.0pre2 crashes dedicated forge server 1.9 build 1811 on startup

### ISSUE THREAD

**Issue by kreezxil** [canitzp/Rarmor#6]
Issue: rarmor-1.9-0.5.0pre2 crashes dedicated forge server 1.9 build 1811 on startup

crash report:
https://gist.github.com/00154e618e05b3fbfdc8

fml server latest:
https://gist.github.com/04d0a1e5c1168ff5ca44

**Comment by canitzp** [comment]
This crashes a lot of Mods, I'll fix it later

**Comment by canitzp** [comment]
Fixed with latest commit and uploaded new Version to CurseForge
