### ISSUE TITLE
1.9-0.5.0 crashes dedicated forge server 1.9 build 1821 on startup

### ISSUE THREAD

**Issue by kreezxil** [canitzp/Rarmor#7]
Issue: rarmor-1.9-0.5.0 crashes dedicated forge server 1.9 build 1821 on startup

crash report:
https://gist.github.com/0bc47850d6ced1ff2ff2af69f57d7c55

fml server latest:
https://gist.github.com/6ddb612685cc1cdc412c69cdbef1966a

**Comment by canitzp** [comment]
Can you test it with the new Forge Version please?

**Comment by canitzp** [comment]
Fixed in Rarmor 0.5.1
